# Generated by Django 5.0.2 on 2024-03-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_task_remindertime'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dueDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
