# Generated by Django 5.0.2 on 2024-03-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reminderTime',
        ),
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
