# Generated by Django 5.0.2 on 2024-02-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_title', models.CharField(max_length=100)),
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
